codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    patch: off
    project:
      default: false
      appPlayer:
        target: 100%
        paths: "packages/@coorpacademy-app-player"
      components:
        target: 94%
        paths: "packages/@coorpacademy-components"
      progressionEngine:
        target: 99%
        paths: "packages/@coorpacademy-progression-engine"
      translate:
        target: 100%
        paths: "packages/@coorpacademy-translate"
      webpackConfig:
        target: 100%
        paths: "packages/@coorpacademy-webpack-config"
