codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    patch: off
    project:
      default: false
      player-store:
        paths: 'packages/@coorpacademy-player-store'
      player-services:
        paths: 'packages/@coorpacademy-player-services'
      player-web:
        paths: 'packages/@coorpacademy-player-web'
      components:
        paths: 'packages/@coorpacademy-components'
      progressionEngine:
        paths: 'packages/@coorpacademy-progression-engine'
      translate:
        paths: 'packages/@coorpacademy-translate'
      webpackConfig:
        paths: 'packages/@coorpacademy-webpack-config'
