const fs = require('fs');
const glob = require('glob');
const path = require('path');
const pascalCase = require('pascal-case');
const includes = '{atom,molecule,organism}';
const title = '/* Generated by src/util/generate-components-index */\n\n';

const reset = index => {
  fs.writeFileSync(index, title);
};

const fixtures = (type, component) => {
  const fixturesPath = `../components/${type}/${component}/test/fixtures/*.js`;
  const fixturesFiles = glob.sync(path.join(__dirname, fixturesPath));

  const fixtures = fixturesFiles.map(function(file) {
    const splinters = file.split('/');
    const fixture = splinters[splinters.length - 1];
    return {
      path: `./${path.join(type, component, 'test/fixtures', fixture)}`,
      name: fixture
    };
  });

  return fixtures;
};

const extract = skipFixtures => {
  const components = `../components/${includes}/**/index.js`;
  const files = glob.sync(path.join(__dirname, components));

  const elements = files.map(function(file) {
    const splinters = file.split('/');
    const component = splinters[splinters.length - 2];
    const type = splinters[splinters.length - 3];
    const name = pascalCase(component);

    return {
      type,
      name,
      factory: `create${name}`,
      path: `./${path.join(type, component)}`,
      fixtures: !skipFixtures && fixtures(type, component)
    };
  });

  return elements;
};

const _exports = elements => {
  const factories = elements.map(element => element.factory);
  return `  ${factories.join(',\n  ')}`;
};

const _imports = elements => {
  const lines = elements.map(e => `import ${e.factory} from '${e.path}'`);
  return `${lines.join(';\n')};`;
};

const generate = () => {
  const index = path.join(__dirname, '../components/index.js');
  const elements = extract(true);

  reset(index);
  fs.appendFileSync(index, `${_imports(elements)}\n`);
  fs.appendFileSync(index, `\nexport {\n${_exports(elements)}\n};\n`);
};

export {
  extract,
  generate
};
