/* Generated by `npm run generate:index` */

import createCenteredText from './atom/centered-text/';
import createImage from './atom/image/';
import createLabelModName from './atom/label-mod-name/';
import createLabelNormal from './atom/label-normal/';
import createLabel from './atom/label/';
import createLink from './atom/link/';
import createSpinner from './atom/spinner/';
import createStar from './atom/star/';
import createTitle from './atom/title/';
import CenteredBehaviour from './behaviour/align/centered/';
import PrimaryBehaviour from './behaviour/color/primary/';
import TextInvertedBehaviour from './behaviour/color/text-inverted/';
import TextNormalBehaviour from './behaviour/color/text-normal/';
import HoverFillBehaviour from './behaviour/effects/hover-fill/';
import RadialFocusBehaviour from './behaviour/effects/radial-focus/';
import EllipsisBehaviour from './behaviour/font/ellipsis/';
import EmbossedBehaviour from './behaviour/font/embossed/';
import NormalBehaviour from './behaviour/font/normal/';
import TinyBehaviour from './behaviour/font/tiny/';
import UppercaseBehaviour from './behaviour/font/uppercase/';
import createCatalogCard from './molecule/catalog-card/';
import createCatalogCta from './molecule/catalog-cta/';
import createCategories from './molecule/categories/';
import createCheckboxes from './molecule/checkboxes/';
import createCursusHeader from './molecule/cursus-header/';
import createCursusList from './molecule/cursus-list/';
import createDisciplineCard from './molecule/discipline-card/';
import createDisciplineHeader from './molecule/discipline-header/';
import createDisciplineScope from './molecule/discipline-scope/';
import createModuleBubble from './molecule/module-bubble/';
import createScopeContent from './molecule/scope-content/';
import createScopeTabs from './molecule/scope-tabs/';
import createSelectBox from './molecule/select-box/';
import createStarRating from './molecule/star-rating/';
import createThemeImage from './molecule/theme-image/';
import createTitledCheckbox from './molecule/titled-checkbox/';
import createVideoIframe from './molecule/video-iframe/';
import createVideoPlayer from './molecule/video-player/';
import createCatalogCards from './organism/catalog-cards/';
import createCursusRightaside from './organism/cursus-rightaside/';
import createDisciplineCards from './organism/discipline-cards/';
import createDisciplineRightaside from './organism/discipline-rightaside/';
import createHero from './organism/hero/';
import createCatalog from './template/app-catalog/catalog/';
import createProductCourse from './template/app-catalog/product-course/';
import createProductCursus from './template/app-catalog/product-cursus/';

export {
  createCenteredText,
  createImage,
  createLabelModName,
  createLabelNormal,
  createLabel,
  createLink,
  createSpinner,
  createStar,
  createTitle,
  CenteredBehaviour,
  PrimaryBehaviour,
  TextInvertedBehaviour,
  TextNormalBehaviour,
  HoverFillBehaviour,
  RadialFocusBehaviour,
  EllipsisBehaviour,
  EmbossedBehaviour,
  NormalBehaviour,
  TinyBehaviour,
  UppercaseBehaviour,
  createCatalogCard,
  createCatalogCta,
  createCategories,
  createCheckboxes,
  createCursusHeader,
  createCursusList,
  createDisciplineCard,
  createDisciplineHeader,
  createDisciplineScope,
  createModuleBubble,
  createScopeContent,
  createScopeTabs,
  createSelectBox,
  createStarRating,
  createThemeImage,
  createTitledCheckbox,
  createVideoIframe,
  createVideoPlayer,
  createCatalogCards,
  createCursusRightaside,
  createDisciplineCards,
  createDisciplineRightaside,
  createHero,
  createCatalog,
  createProductCourse,
  createProductCursus
};
