const fs = require('fs');
const path = require('path');
const {extractComponents} = require('./components-finder');

const writeExports = elements => {
  const factories = elements.map(element => element.factory);
  return `  ${factories.join(',\n  ')}`;
};

const writeImports = elements => {
  const lines = elements.map(e => `import ${e.factory} from '${e.path}'`);
  return `${lines.join(';\n')};`;
};

const write = (index, content) => {
  const title = '/* Generated by `npm run generate:index` */\n\n';
  fs.writeFileSync(index, `${title}${content}`);
};

const generate = () => {
  const index = path.join(__dirname, '../index.js');
  const includes = '{atom,behaviour,molecule,organism,template}';
  const elements = extractComponents(includes, true);

  const _imports = `${writeImports(elements)}\n`;
  const _exports = `export {\n${writeExports(elements)}\n};\n`;

  const content = `${_imports}\n${_exports}`;

  write(index, content);
};

module.exports = generate;

if (!module.parent) {
  generate();
}
