/* Generated by src/util/generate-components-index */

import createLabelModName from './atom/label-mod-name/';
import createLabelNormal from './atom/label-normal/';
import createLabel from './atom/label/';
import createTitle from './atom/title/';
import CenteredBehaviour from './behaviour/align/centered/';
import PrimaryBehaviour from './behaviour/color/primary/';
import TextInvertedBehaviour from './behaviour/color/text-inverted/';
import TextNormalBehaviour from './behaviour/color/text-normal/';
import EllipsisBehaviour from './behaviour/font/ellipsis/';
import EmbossedBehaviour from './behaviour/font/embossed/';
import NormalBehaviour from './behaviour/font/normal/';
import TinyBehaviour from './behaviour/font/tiny/';
import UppercaseBehaviour from './behaviour/font/uppercase/';
import createCheckboxes from './molecule/checkboxes/';
import createDisciplineCard from './molecule/discipline-card/';
import createModuleBubble from './molecule/module-bubble/';
import createSelectBox from './molecule/select-box/';
import createTitledCheckbox from './molecule/titled-checkbox/';
import createDisciplineCards from './organism/discipline-cards/';

export {
  createLabelModName,
  createLabelNormal,
  createLabel,
  createTitle,
  CenteredBehaviour,
  PrimaryBehaviour,
  TextInvertedBehaviour,
  TextNormalBehaviour,
  EllipsisBehaviour,
  EmbossedBehaviour,
  NormalBehaviour,
  TinyBehaviour,
  UppercaseBehaviour,
  createCheckboxes,
  createDisciplineCard,
  createModuleBubble,
  createSelectBox,
  createTitledCheckbox,
  createDisciplineCards
};
