const fs = require('fs');
const path = require('path');
const {extractComponents} = require('./@coorpacademy/components/util/components-finder');

const writeExports = elements => {
  const factories = elements.map(element => element.factory);
  return `  ${factories.join(',\n  ')}`;
};

const writeImports = elements => {
  const lines = elements.map(e => `import ${e.factory} from './@coorpacademy/components/${e.path}'`);
  return `${lines.join(';\n')};`;
};

const reset = index => {
  const title = '/* Generated by src/util/generate-bundle.js */\n\n';
  fs.writeFileSync(index, title);
};

const generate = () => {
  const index = path.join(__dirname, './index.js');
  const includes = '{atom,behaviour,molecule,organism,template}';
  const elements = extractComponents(includes, true);

  const _imports = `${writeImports(elements)}\n`;
  const _exports = `\nexport {\n${writeExports(elements)}\n};\n`;

  reset(index);
  fs.appendFileSync(index, _imports);
  fs.appendFileSync(index, _exports);
};

module.exports = {
  generate
};

if (!module.parent) {
  generate();
}
